# Action: Setup Project (composite action)
#
# Purpose: Bootstrap a Python project within GitHub Actions by:
#   - Installing uv and uvx into a local ./bin directory and adding it to PATH
#   - Detecting the presence of pyproject.toml and exposing that as an output
#   - Creating a virtual environment with uv and (optionally) syncing dependencies
#
# Inputs:
#   - python-version: Python version for the uv-managed virtual environment (default: 3.12)
#
# Outputs:
#   - pyproject_exists: "true" if pyproject.toml exists, otherwise "false"
#
# Notes:
#   - Safe to run in repositories without pyproject.toml; dependency sync will be skipped.
#   - Purely a CI helper — it does not modify repository files.

name: 'Setup Project'
description: 'Setup the project'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

outputs:
  pyproject_exists:
    description: 'Flag indicating whether pyproject.toml exists'
    value: ${{ steps.check_pyproject.outputs.exists }}

runs:
  using: 'composite'
  steps:
    - name: Set up uv, uvx and the venv
      shell: bash
      run: |
        mkdir -p bin

        # Add ./bin to the PATH
        echo "Adding ./bin to PATH"
        echo "$(pwd)/bin" >> $GITHUB_PATH

        # Install uv and uvx
        curl -fsSL https://astral.sh/uv/install.sh | UV_INSTALL_DIR="./bin" sh

    - name: Check version for uv
      shell: bash
      run: |
        uv --version

    - name: Check for pyproject.toml
      id: check_pyproject
      shell: bash
      run: |
        if [ -f "pyproject.toml" ]; then
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Build the virtual environment
      shell: bash
      run: uv venv --python ${{ inputs.python-version }}

    - name: "Sync the virtual environment for ${{ github.repository }} if pyproject.toml exists"
      shell: bash
      run: |
        if [ -f "pyproject.toml" ]; then
          uv sync --all-extras
        else
          echo "No pyproject.toml found, skipping package installation"
        fi

    - name: Show dependencies
      shell: bash
      run: uv pip list

    - name: Show Python version
      shell: bash
      run: uv run python -c "import sys; print(sys.version)"
